"""
This file contains the code for testing samples.
"""

adjs = ['Absurd', 'Abundant', 'Addictive', 'Adorable', 'Aged', 'Amazing', 'American', 'Ancient', 'Animated', 'Annoying']
nouns = ['Saturn', 'The Baby-Sitters Club', 'Writing A Letter', 'Rap Music', 'Star Fruit', 'Jacques Cousteau', 'Ginseng', 'Sand Castles', 'Fireworks', 'Men']
test = [f'Dumb and Dumber {noun}' for noun in nouns]
print(test)

nouns2 = ['Black Holes', 'Michael Jordon', 'Terrorist Attack', 'Beef Stew', 'Perfume', 'Having A Baby', 'Bumble Bees', 'Pillows', 'Rock And Roll', 'Dodo Birds']
samples = [
    'Absurd Saturn',
    'Absurd The Baby-Sitters Club',
    'Absurd Writing A Letter',
    'Absurd Rap Music',
    'Absurd Star Fruit',
    'Absurd Jacques Cousteau',
    'Absurd Ginseng',
    'Absurd Sand Castles',
    'Absurd Fireworks',
    'Absurd Men',
    'Abundant Saturn',
    'Abundant The Baby-Sitters Club',
    'Abundant Writing A Letter',
    'Abundant Rap Music',
    'Abundant Star Fruit',
    'Abundant Jacques Cousteau',
    'Abundant Ginseng',
    'Abundant Sand Castles',
    'Abundant Fireworks',
    'Abundant Men',
    'Addictive Saturn',
    'Addictive The Baby-Sitters Club',
    'Addictive Writing A Letter',
    'Addictive Rap Music',
    'Addictive Star Fruit',
    'Addictive Jacques Cousteau',
    'Addictive Ginseng',
    'Addictive Sand Castles',
    'Addictive Fireworks',
    'Addictive Men',
    'Adorable Saturn',
    'Adorable The Baby-Sitters Club',
    'Adorable Writing A Letter',
    'Adorable Rap Music',
    'Adorable Star Fruit',
    'Adorable Jacques Cousteau',
    'Adorable Ginseng',
    'Adorable Sand Castles',
    'Adorable Fireworks',
    'Adorable Men',
    'Aged Saturn',
    'Aged The Baby-Sitters Club',
    'Aged Writing A Letter',
    'Aged Rap Music',
    'Aged Star Fruit',
    'Aged Jacques Cousteau',
    'Aged Ginseng',
    'Aged Sand Castles',
    'Aged Fireworks',
    'Aged Men',
    'Amazing Saturn',
    'Amazing The Baby-Sitters Club',
    'Amazing Writing A Letter',
    'Amazing Rap Music',
    'Amazing Star Fruit',
    'Amazing Jacques Cousteau',
    'Amazing Ginseng',
    'Amazing Sand Castles',
    'Amazing Fireworks',
    'Amazing Men',
    'American Saturn',
    'American The Baby-Sitters Club',
    'American Writing A Letter',
    'American Rap Music',
    'American Star Fruit',
    'American Jacques Cousteau',
    'American Ginseng',
    'American Sand Castles',
    'American Fireworks',
    'American Men',
    'Ancient Saturn',
    'Ancient The Baby-Sitters Club',
    'Ancient Writing A Letter',
    'Ancient Rap Music',
    'Ancient Star Fruit',
    'Ancient Jacques Cousteau',
    'Ancient Ginseng',
    'Ancient Sand Castles',
    'Ancient Fireworks',
    'Ancient Men',
    'Animated Saturn',
    'Animated The Baby-Sitters Club',
    'Animated Writing A Letter',
    'Animated Rap Music',
    'Animated Star Fruit',
    'Animated Jacques Cousteau',
    'Animated Ginseng',
    'Animated Sand Castles',
    'Animated Fireworks',
    'Animated Men',
    'Annoying Saturn',
    'Annoying The Baby-Sitters Club',
    'Annoying Writing A Letter',
    'Annoying Rap Music',
    'Annoying Star Fruit',
    'Annoying Jacques Cousteau',
    'Annoying Ginseng',
    'Annoying Sand Castles',
    'Annoying Fireworks',
    'Annoying Men'
]

print(nouns+nouns2)